print("Olá, Mundo")
print("Oii Carlos")
print("So queria dormir mdss")
print("Amoo o São Paulo")
print("você parece vcom vergonha, ajulicosta e foda")
print("Mds quero minhas ferias")
print("ainda bem que e sexta feira não aguentava mais ")
print(" quero colocar minhas tranças logooo")
print("quero minha casa")
print("espero realmente aprender python")